name: monorepo
packages:
  - packages/**
  - apps/**
scripts:
  bootstrap:
    description: Bootstrap the workspace
    run: melos bootstrap
  clean:
    description: Clean the workspace
    run: melos clean
  test:
    description: Run tests for all packages
    run: melos run test

command:
  bootstrap:
    usePubspecOverrides: true